# General info: https://docs.gitlab.com/ee/ci/yaml/
# Building maven: https://docs.gitlab.com/ee/user/project/packages/maven_repository.html

services:
  - mariadb:10.3

variables:
  # Configure mysql environment variables (https://hub.docker.com/_/mariadb/)
  MYSQL_DATABASE: "root"
  MYSQL_ROOT_PASSWORD: ""
  MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

  # This will suppress any download for dependencies and plugins or upload messages which would clutter the console log.
  # `showDateTime` will show the passed time in milliseconds. You need to specify `--batch-mode` to make this work.
  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  # As of Maven 3.3.0 instead of this you may define these options in `.mvn/maven.config` so the same config is used
  # when running from the command line.
  # `installAtEnd` and `deployAtEnd` are only effective with recent version of the corresponding plugins.
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"

# Cache downloaded dependencies and plugins between builds.
# To keep cache across branches add 'key: "$CI_JOB_NAME"'
cache:
  paths:
    - .m2/repository

.compile:
  stage: build
  before_script:
    - echo -e "section_start:`date +%s`:install_packages[collapsed=true]\r\e[0K\e[1;96mInstalling packages\e[0m"
    - apt-get update -qq
    - apt-get install -qq -y mariadb-client
    - echo -e "section_end:`date +%s`:install_packages\r\e[0K"
    - perl -pi -e 's|localhost/[a-zA-Z0-9]+|mariadb/abgabesystem|g' src/main/resources/hibernate.cfg.xml
  script:
    - 'mvn $MAVEN_CLI_OPTS verify'
    - mysql -u root -h mariadb -e 'create database abgabesystem CHARACTER SET = utf8mb4 COLLATE = utf8mb4_bin;'
    - mysql -u root -h mariadb abgabesystem < mysql.sql
    - mvn exec:java -Dexec.mainClass="de.tuclausthal.submissioninterface.util.CreateFirstUser" -Dexec.args="admin admin@localhost Firstname Lastname"
    - mvn exec:java -Dexec.mainClass="de.tuclausthal.submissioninterface.util.HibernateSQLExporter"
  # keep built artifacts
  artifacts:
    paths:
      - target/*.war
      - 1.sql
    expire_in: 1 week

compile-jdk8:
    extends: .compile
    image: maven:3.6.3-jdk-8

compile-jdk11:
    extends: .compile
    image: maven:3.6.3-jdk-11
